# qbittorrent.yaml (Revised with NodePort)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      nodeSelector:
        kubernetes.io/hostname: ubuntu-k8s-worker-3
      containers:
      - name: qbittorrent-app
        image: lscr.io/linuxserver/qbittorrent:latest
        ports:
        - name: webui
          containerPort: 8080
        - name: torrent-p2p
          containerPort: 6881
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Sarajevo"
        - name: WEBUI_PORT
          value: "8080"
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: torrent-data
          mountPath: /downloads
      volumes:
      - name: qbittorrent-config
        hostPath:
          path: /mnt/media_storage/qbittorrent_config
          type: DirectoryOrCreate
      - name: torrent-data
        hostPath:
          path: /mnt/media_storage/torrents_data
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-webui-service
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
  - name: webui-http
    protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-p2p-service
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
  - name: p2p-tcp
    protocol: TCP
    port: 6881
    targetPort: 6881
    nodePort: 30681
  - name: p2p-udp
    protocol: UDP
    port: 6881
    targetPort: 6881
    nodePort: 30681

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare-issuer"
spec:
  tls:
  - hosts:
    - torrent.nhukovic.com
    secretName: torrent-tls-secret
  rules:
  - host: "torrent.nhukovic.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent-webui-service
            port:
              number: 8080