# nextcloud-external.yaml - manual endpoint

# Servis
# Kreiramo "headless" service, setting clusterIP: None.
# Ovo kaze k8su ja cu provide endpoints, ti ne moras nista za mene
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-manual-service # Using a new name to avoid confusion
  namespace: default
spec:
  # prt 80 koristimo na nextcloud strani
  ports:
  - port: 80
    targetPort: 80

---

# endpoint dio
# objekat mora imati isto ime kao gore
# dajemo IP kubernetiesu ovdje
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud-manual-service # MORA biti isto ime kao gore
  namespace: default
subsets:
  - addresses:
    - ip: 192.168.50.4 # IP servera realni
    ports:
    - port: 80

---

# Ingress
# Updatovat cemo manuelno ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare-issuer"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "15552000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50G"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nextcloud.nhukovic.com
    secretName: nextcloud-tls-secret
  rules:
  - host: "nextcloud.nhukovic.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Pointa na novo servisno ime
            name: nextcloud-manual-service
            port:
              number: 80